In [2]:
import pandas as pd
import matplotlib.pyplot as plot
import seaborn as sns

In [6]:
df = pd.read_csv("/content/drive/MyDrive/file/healthcare_dataset.csv")
df

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date
0,P1001,Male,45,Hypertension,15-01-2026,Urgent,ICD-10-I10,4500.0,20-01-2026
1,P1002,Female,32,Pneumonia,16-01-2026,Emergency,ICD-10-J18,6700.5,22-01-2026
2,P1003,Male,68,Diabetes Type 2,16-01-2026,Routine,ICD-10-E11,3200.0,18-01-2026
3,P1004,Female,55,Asthma,17-01-2026,Emergency,ICD-10-J45,5800.0,19-01-2026
4,P1005,Male,29,Fracture,17-01-2026,Urgent,ICD-10-S52,8500.0,25-01-2026
...,...,...,...,...,...,...,...,...,...
495,P1496,Female,50,COPD,20-09-2026,Emergency,ICD-10-J44,9800.0,23-09-2026
496,P1497,Male,28,Fracture,20-09-2026,Urgent,ICD-10-S52,9400.0,24-09-2026
497,P1498,Female,67,Heart Attack,21-09-2026,Emergency,ICD-10-I21,14200.0,25-09-2026
498,P1499,Male,43,Diabetes Type 2,21-09-2026,Routine,ICD-10-E11,4900.0,23-09-2026
499,P1500,Female,61,Stroke,22-09-2026,Emergency,ICD-10-I63,13900.0,26-09-2026

In [7]:
df.head()

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date
0,P1001,Male,45,Hypertension,15-01-2026,Urgent,ICD-10-I10,4500.0,20-01-2026
1,P1002,Female,32,Pneumonia,16-01-2026,Emergency,ICD-10-J18,6700.5,22-01-2026
2,P1003,Male,68,Diabetes Type 2,16-01-2026,Routine,ICD-10-E11,3200.0,18-01-2026
3,P1004,Female,55,Asthma,17-01-2026,Emergency,ICD-10-J45,5800.0,19-01-2026
4,P1005,Male,29,Fracture,17-01-2026,Urgent,ICD-10-S52,8500.0,25-01-2026

In [8]:
df.head()

,Patient_ID,Gender,Age,Medical_Condition,Admission_Date,Admission_Type,Medical_Code,Billing_Amount,Discharge_Date
0,P1001,Male,45,Hypertension,15-01-2026,Urgent,ICD-10-I10,4500.0,20-01-2026
1,P1002,Female,32,Pneumonia,16-01-2026,Emergency,ICD-10-J18,6700.5,22-01-2026
2,P1003,Male,68,Diabetes Type 2,16-01-2026,Routine,ICD-10-E11,3200.0,18-01-2026
3,P1004,Female,55,Asthma,17-01-2026,Emergency,ICD-10-J45,5800.0,19-01-2026
4,P1005,Male,29,Fracture,17-01-2026,Urgent,ICD-10-S52,8500.0,25-01-2026

In [9]:
df.describe()

              Age  Billing_Amount
count  500.000000       500.00000
mean    50.106000      7249.00100
std     15.328035      3198.96932
min     22.000000      2300.00000
25%     37.000000      4400.00000
50%     50.000000      6950.00000
75%     63.000000      9400.00000
max     78.000000     14200.00000

In [10]:
df.isnull().sum()

Patient_ID           0
Gender               0
Age                  0
Medical_Condition    0
Admission_Date       0
Admission_Type       0
Medical_Code         0
Billing_Amount       0
Discharge_Date       0
dtype: int64

In [11]:
for column in df.select_dtypes(include='object').columns:
    df[column] = df[column].fillna('Unknown')

print("Missing values after filling:")
print(df.isnull().sum())

Missing values after filling:
Patient_ID           0
Gender               0
Age                  0
Medical_Condition    0
Admission_Date       0
Admission_Type       0
Medical_Code         0
Billing_Amount       0
Discharge_Date       0
dtype: int64

In [12]:
df['Admission_Date'] = pd.to_datetime(df['Admission_Date'])
df['Discharge_Date'] = pd.to_datetime(df['Discharge_Date'])

/tmp/ipykernel_817/1900966036.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Admission_Date'] = pd.to_datetime(df['Admission_Date'])
/tmp/ipykernel_817/1900966036.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Discharge_Date'] = pd.to_datetime(df['Discharge_Date'])

In [13]:
print(df['Admission_Date'].dtype)
print(df['Discharge_Date'].dtype)

datetime64[ns]
datetime64[ns]

In [14]:
df['Medical_Code'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Name: Medical_Code, Length: 500, dtype: bool

In [15]:
print(df['Admission_Type'].value_counts())

Admission_Type
Routine      196
Emergency    188
Urgent       116
Name: count, dtype: int64

In [16]:
df['Admission_Type'] = df['Admission_Type'].str.lower()

In [19]:
df['Hospital_Stay_Days'] = (df['Discharge_Date'] - df['Admission_Date']).dt.days
df['Hospital_Stay_Days'].describe()

count    500.00000
mean       2.74400
std        1.17696
min        1.00000
25%        2.00000
50%        2.00000
75%        4.00000
max       10.00000
Name: Hospital_Stay_Days, dtype: float64

In [18]:
df['Hospital_Stay_Days'] = (df['Discharge_Date'] - df['Admission_Date']).dt.days
print(df['Billing_Amount'].describe())
print(df['Hospital_Stay_Days'].describe())

count      500.00000
mean      7249.00100
std       3198.96932
min       2300.00000
25%       4400.00000
50%       6950.00000
75%       9400.00000
max      14200.00000
Name: Billing_Amount, dtype: float64
count    500.00000
mean       2.74400
std        1.17696
min        1.00000
25%        2.00000
50%        2.00000
75%        4.00000
max       10.00000
Name: Hospital_Stay_Days, dtype: float64